import type { Flashcard, Level, LevelInfo } from '@/types/database';

export const LEVEL_INFO: Record<Level, LevelInfo & { emoji: string; color: string; bg: string; border: string }> = {
  A1: { id:'A1', name:'Principiante',     emoji:'🌱', description:'Palabras básicas y frases del día a día',           color:'text-emerald-300', bg:'bg-emerald-500/10', border:'border-emerald-500/30', totalCards:20, minXP:0    },
  A2: { id:'A2', name:'Básico',           emoji:'🌿', description:'Conversaciones simples sobre temas familiares',      color:'text-emerald-400', bg:'bg-emerald-500/15', border:'border-emerald-500/40', totalCards:20, minXP:200  },
  B1: { id:'B1', name:'Intermedio',       emoji:'🌳', description:'Trabajo, viajes y situaciones cotidianas',           color:'text-emerald-400', bg:'bg-emerald-500/20', border:'border-emerald-500/50', totalCards:20, minXP:600  },
  B2: { id:'B2', name:'Intermedio Alto',  emoji:'🌲', description:'Textos complejos y temas abstractos',               color:'text-emerald-300', bg:'bg-emerald-600/20', border:'border-emerald-400/50', totalCards:20, minXP:1400 },
  C1: { id:'C1', name:'Avanzado',         emoji:'🏔️', description:'Lenguaje fluido y bien estructurado',               color:'text-teal-300',    bg:'bg-teal-500/15',    border:'border-teal-500/40',    totalCards:20, minXP:2600 },
  C2: { id:'C2', name:'Maestría',         emoji:'👑', description:'Comprensión y expresión con total precisión',       color:'text-teal-200',    bg:'bg-teal-400/15',    border:'border-teal-400/40',    totalCards:20, minXP:4200 },
};

export const FLASHCARDS: Flashcard[] = [
  // A1
  { id:'a1_01', level:'A1', category:'Saludos',     front:'Hello',         back:'Hola',           example:'Hello! How are you?',              example_es:'¡Hola! ¿Cómo estás?' },
  { id:'a1_02', level:'A1', category:'Saludos',     front:'Good morning',  back:'Buenos días',    example:'Good morning, everyone!',          example_es:'¡Buenos días a todos!' },
  { id:'a1_03', level:'A1', category:'Cortesía',    front:'Thank you',     back:'Gracias',        example:'Thank you very much!',             example_es:'¡Muchas gracias!' },
  { id:'a1_04', level:'A1', category:'Cortesía',    front:'Please',        back:'Por favor',      example:'Can you help me, please?',         example_es:'¿Me puedes ayudar, por favor?' },
  { id:'a1_05', level:'A1', category:'Números',     front:'One / Two / Three', back:'Uno / Dos / Tres', example:'I have three cats.',         example_es:'Tengo tres gatos.' },
  { id:'a1_06', level:'A1', category:'Colores',     front:'Red',           back:'Rojo',           example:'The apple is red.',                example_es:'La manzana es roja.' },
  { id:'a1_07', level:'A1', category:'Colores',     front:'Blue',          back:'Azul',           example:'The sky is blue.',                 example_es:'El cielo es azul.' },
  { id:'a1_08', level:'A1', category:'Familia',     front:'Mother',        back:'Madre',          example:'My mother is very kind.',          example_es:'Mi madre es muy amable.' },
  { id:'a1_09', level:'A1', category:'Familia',     front:'Father',        back:'Padre',          example:'My father works hard.',            example_es:'Mi padre trabaja mucho.' },
  { id:'a1_10', level:'A1', category:'Comida',      front:'Water',         back:'Agua',           example:'I drink water every day.',         example_es:'Bebo agua todos los días.' },
  { id:'a1_11', level:'A1', category:'Comida',      front:'Bread',         back:'Pan',            example:'I eat bread for breakfast.',       example_es:'Como pan en el desayuno.' },
  { id:'a1_12', level:'A1', category:'Verbos',      front:'To eat',        back:'Comer',          example:'I eat rice for lunch.',            example_es:'Como arroz al almuerzo.' },
  { id:'a1_13', level:'A1', category:'Verbos',      front:'To sleep',      back:'Dormir',         example:'I sleep eight hours.',             example_es:'Duermo ocho horas.' },
  { id:'a1_14', level:'A1', category:'Verbos',      front:'To go',         back:'Ir',             example:'I go to school every day.',        example_es:'Voy a la escuela todos los días.' },
  { id:'a1_15', level:'A1', category:'Lugares',     front:'School',        back:'Escuela',        example:'The school is near my house.',     example_es:'La escuela está cerca de mi casa.' },
  { id:'a1_16', level:'A1', category:'Lugares',     front:'House',         back:'Casa',           example:'My house is big.',                 example_es:'Mi casa es grande.' },
  { id:'a1_17', level:'A1', category:'Tiempo',      front:'Today',         back:'Hoy',            example:'Today is Monday.',                 example_es:'Hoy es lunes.' },
  { id:'a1_18', level:'A1', category:'Tiempo',      front:'Tomorrow',      back:'Mañana',         example:'Tomorrow I have a test.',          example_es:'Mañana tengo un examen.' },
  { id:'a1_19', level:'A1', category:'Adjetivos',   front:'Big',           back:'Grande',         example:'The elephant is very big.',        example_es:'El elefante es muy grande.' },
  { id:'a1_20', level:'A1', category:'Adjetivos',   front:'Small',         back:'Pequeño/a',      example:'The cat is very small.',           example_es:'El gato es muy pequeño.' },
  // A2
  { id:'a2_01', level:'A2', category:'Vida diaria', front:'Busy',          back:'Ocupado/a',      example:'I am busy this afternoon.',        example_es:'Estoy ocupado esta tarde.' },
  { id:'a2_02', level:'A2', category:'Vida diaria', front:'Tired',         back:'Cansado/a',      example:'She is tired after work.',         example_es:'Ella está cansada después del trabajo.' },
  { id:'a2_03', level:'A2', category:'Compras',     front:'Expensive',     back:'Caro/a',         example:'This jacket is too expensive.',    example_es:'Esta chaqueta es demasiado cara.' },
  { id:'a2_04', level:'A2', category:'Compras',     front:'Cheap',         back:'Barato/a',       example:'The market has cheap vegetables.', example_es:'El mercado tiene verduras baratas.' },
  { id:'a2_05', level:'A2', category:'Transporte',  front:'Bus',           back:'Autobús',        example:'I take the bus to work.',          example_es:'Tomo el autobús al trabajo.' },
  { id:'a2_06', level:'A2', category:'Transporte',  front:'Airport',       back:'Aeropuerto',     example:'We arrived at the airport early.', example_es:'Llegamos al aeropuerto temprano.' },
  { id:'a2_07', level:'A2', category:'Salud',       front:'Doctor',        back:'Médico/a',       example:'I need to see a doctor.',          example_es:'Necesito ver a un médico.' },
  { id:'a2_08', level:'A2', category:'Salud',       front:'Headache',      back:'Dolor de cabeza',example:'I have a terrible headache.',      example_es:'Tengo un terrible dolor de cabeza.' },
  { id:'a2_09', level:'A2', category:'Clima',       front:'Cloudy',        back:'Nublado/a',      example:'It is cloudy outside today.',      example_es:'Hoy está nublado afuera.' },
  { id:'a2_10', level:'A2', category:'Clima',       front:'Rainy',         back:'Lluvioso/a',     example:'April is very rainy here.',        example_es:'Abril es muy lluvioso aquí.' },
  { id:'a2_11', level:'A2', category:'Verbos',      front:'To understand', back:'Entender',       example:'Do you understand the lesson?',    example_es:'¿Entiendes la lección?' },
  { id:'a2_12', level:'A2', category:'Verbos',      front:'To remember',   back:'Recordar',       example:'I cannot remember his name.',      example_es:'No puedo recordar su nombre.' },
  { id:'a2_13', level:'A2', category:'Verbos',      front:'To help',       back:'Ayudar',         example:'Can you help me with this?',       example_es:'¿Me puedes ayudar con esto?' },
  { id:'a2_14', level:'A2', category:'Verbos',      front:'To learn',      back:'Aprender',       example:'I want to learn English.',         example_es:'Quiero aprender inglés.' },
  { id:'a2_15', level:'A2', category:'Trabajo',     front:'Meeting',       back:'Reunión',        example:'We have a meeting at noon.',       example_es:'Tenemos una reunión al mediodía.' },
  { id:'a2_16', level:'A2', category:'Trabajo',     front:'Office',        back:'Oficina',        example:'My office is on the third floor.', example_es:'Mi oficina está en el tercer piso.' },
  { id:'a2_17', level:'A2', category:'Comida',      front:'Delicious',     back:'Delicioso/a',    example:'This food is absolutely delicious!',example_es:'¡Esta comida está absolutamente deliciosa!' },
  { id:'a2_18', level:'A2', category:'Pasatiempos', front:'Reading',       back:'Lectura / Leer', example:'Reading is my favorite hobby.',    example_es:'Leer es mi pasatiempo favorito.' },
  { id:'a2_19', level:'A2', category:'Pasatiempos', front:'Travelling',    back:'Viajar',         example:'I love travelling to new places.', example_es:'Me encanta viajar a nuevos lugares.' },
  { id:'a2_20', level:'A2', category:'Comunicación',front:'To explain',    back:'Explicar',       example:'Please explain the problem again.',example_es:'Por favor explica el problema de nuevo.' },
  // B1
  { id:'b1_01', level:'B1', category:'Trabajo',     front:'Deadline',      back:'Fecha límite',   example:'The deadline is next Friday.',     example_es:'La fecha límite es el próximo viernes.' },
  { id:'b1_02', level:'B1', category:'Trabajo',     front:'Promotion',     back:'Ascenso',        example:'She got a promotion last month.',  example_es:'Ella recibió un ascenso el mes pasado.' },
  { id:'b1_03', level:'B1', category:'Medio ambiente',front:'Pollution',   back:'Contaminación',  example:'Air pollution is a global problem.',example_es:'La contaminación del aire es un problema global.' },
  { id:'b1_04', level:'B1', category:'Medio ambiente',front:'Recycling',   back:'Reciclaje',      example:'Recycling helps protect the planet.',example_es:'El reciclaje ayuda a proteger el planeta.' },
  { id:'b1_05', level:'B1', category:'Tecnología',  front:'Software',      back:'Programa / Software',example:'I need to update my software.',example_es:'Necesito actualizar mi programa.' },
  { id:'b1_06', level:'B1', category:'Tecnología',  front:'Device',        back:'Dispositivo',    example:'This device is very easy to use.', example_es:'Este dispositivo es muy fácil de usar.' },
  { id:'b1_07', level:'B1', category:'Frases',      front:'In my opinion', back:'En mi opinión',  example:'In my opinion, we should wait.',   example_es:'En mi opinión, deberíamos esperar.' },
  { id:'b1_08', level:'B1', category:'Frases',      front:'On the other hand',back:'Por otro lado',example:'On the other hand, it could work.',example_es:'Por otro lado, podría funcionar.' },
  { id:'b1_09', level:'B1', category:'Verbos',      front:'To achieve',    back:'Lograr / Alcanzar',example:'She achieved her goals this year.',example_es:'Ella logró sus metas este año.' },
  { id:'b1_10', level:'B1', category:'Verbos',      front:'To improve',    back:'Mejorar',        example:'Practice helps you improve quickly.',example_es:'La práctica te ayuda a mejorar rápido.' },
  { id:'b1_11', level:'B1', category:'Viajes',      front:'Reservation',   back:'Reservación',    example:'I made a hotel reservation online.',example_es:'Hice una reservación de hotel en línea.' },
  { id:'b1_12', level:'B1', category:'Viajes',      front:'Customs',       back:'Aduana',         example:'You must declare items at customs.',example_es:'Debes declarar artículos en la aduana.' },
  { id:'b1_13', level:'B1', category:'Emociones',   front:'Frustrated',    back:'Frustrado/a',    example:'I feel frustrated when I make mistakes.',example_es:'Me siento frustrado cuando cometo errores.' },
  { id:'b1_14', level:'B1', category:'Emociones',   front:'Confident',     back:'Seguro/a de sí mismo',example:'She is confident in her abilities.',example_es:'Ella está segura de sus capacidades.' },
  { id:'b1_15', level:'B1', category:'Sociedad',    front:'Government',    back:'Gobierno',       example:'The government passed a new law.',  example_es:'El gobierno aprobó una nueva ley.' },
  { id:'b1_16', level:'B1', category:'Sociedad',    front:'Poverty',       back:'Pobreza',        example:'Poverty is a complex social issue.', example_es:'La pobreza es un problema social complejo.' },
  { id:'b1_17', level:'B1', category:'Salud',       front:'Surgeon',       back:'Cirujano/a',     example:'The surgeon performed a difficult operation.',example_es:'El cirujano realizó una operación difícil.' },
  { id:'b1_18', level:'B1', category:'Salud',       front:'Vaccine',       back:'Vacuna',         example:'Get your vaccine to stay healthy.', example_es:'Vacúnate para mantenerte sano.' },
  { id:'b1_19', level:'B1', category:'Educación',   front:'Research',      back:'Investigación',  example:'The research took two years.',      example_es:'La investigación tardó dos años.' },
  { id:'b1_20', level:'B1', category:'Educación',   front:'Scholarship',   back:'Beca',           example:'She won a full scholarship.',       example_es:'Ella ganó una beca completa.' },
  // B2
  { id:'b2_01', level:'B2', category:'Negocios',    front:'Negotiate',     back:'Negociar',       example:'We need to negotiate the terms.',   example_es:'Necesitamos negociar los términos.' },
  { id:'b2_02', level:'B2', category:'Negocios',    front:'Revenue',       back:'Ingresos',       example:'Revenue increased by 20% this year.',example_es:'Los ingresos aumentaron un 20% este año.' },
  { id:'b2_03', level:'B2', category:'Conectores',  front:'Nevertheless',  back:'Sin embargo',    example:'It was hard; nevertheless, she succeeded.',example_es:'Fue difícil; sin embargo, ella tuvo éxito.' },
  { id:'b2_04', level:'B2', category:'Conectores',  front:'Furthermore',   back:'Además',         example:'It is fast; furthermore, it is cheap.',example_es:'Es rápido; además, es barato.' },
  { id:'b2_05', level:'B2', category:'Ciencia',     front:'Hypothesis',    back:'Hipótesis',      example:'The scientist tested his hypothesis.',example_es:'El científico probó su hipótesis.' },
  { id:'b2_06', level:'B2', category:'Ciencia',     front:'Evidence',      back:'Evidencia',      example:'There is strong evidence for this theory.',example_es:'Hay evidencia sólida de esta teoría.' },
  { id:'b2_07', level:'B2', category:'Expresiones', front:'To take for granted',back:'Dar por sentado',example:"Don't take your health for granted.",example_es:'No des tu salud por sentada.' },
  { id:'b2_08', level:'B2', category:'Expresiones', front:'To keep in mind',back:'Tener en cuenta',example:'Keep in mind that rules may change.',example_es:'Ten en cuenta que las reglas pueden cambiar.' },
  { id:'b2_09', level:'B2', category:'Abstracto',   front:'Perspective',   back:'Perspectiva',    example:'Let me share a different perspective.',example_es:'Déjame compartir una perspectiva diferente.' },
  { id:'b2_10', level:'B2', category:'Abstracto',   front:'Consequence',   back:'Consecuencia',   example:'Every action has a consequence.',   example_es:'Cada acción tiene una consecuencia.' },
  { id:'b2_11', level:'B2', category:'Medios',      front:'Bias',          back:'Sesgo',          example:'Media bias affects public opinion.', example_es:'El sesgo mediático afecta la opinión pública.' },
  { id:'b2_12', level:'B2', category:'Medios',      front:'Reliable',      back:'Confiable',      example:'Is this a reliable source?',         example_es:'¿Es esta una fuente confiable?' },
  { id:'b2_13', level:'B2', category:'Economía',    front:'Inflation',     back:'Inflación',      example:'Inflation has risen sharply.',       example_es:'La inflación ha subido bruscamente.' },
  { id:'b2_14', level:'B2', category:'Economía',    front:'Unemployment',  back:'Desempleo',      example:'Unemployment fell to a record low.', example_es:'El desempleo cayó a un mínimo histórico.' },
  { id:'b2_15', level:'B2', category:'Verbos',      front:'To anticipate', back:'Anticipar',      example:'We did not anticipate this problem.',example_es:'No anticipamos este problema.' },
  { id:'b2_16', level:'B2', category:'Verbos',      front:'To implement',  back:'Implementar',    example:'The team will implement the strategy.',example_es:'El equipo implementará la estrategia.' },
  { id:'b2_17', level:'B2', category:'Cultura',     front:'Diverse',       back:'Diverso/a',      example:'Our city is culturally very diverse.',example_es:'Nuestra ciudad es culturalmente muy diversa.' },
  { id:'b2_18', level:'B2', category:'Cultura',     front:'Heritage',      back:'Patrimonio',     example:'Colombia has a rich cultural heritage.',example_es:'Colombia tiene un rico patrimonio cultural.' },
  { id:'b2_19', level:'B2', category:'Avanzado',    front:'Ambiguous',     back:'Ambiguo/a',      example:'His answer was deliberately ambiguous.',example_es:'Su respuesta fue deliberadamente ambigua.' },
  { id:'b2_20', level:'B2', category:'Avanzado',    front:'Comprehensive', back:'Exhaustivo/a',   example:'She wrote a comprehensive report.',  example_es:'Ella escribió un informe exhaustivo.' },
];

export function getCardsByLevel(level: Level): Flashcard[] {
  return FLASHCARDS.filter(c => c.level === level);
}
