import type { ExamQuestion } from './examTypes';

export const B1_QUESTIONS: ExamQuestion[] = [
  // ── VOCABULARIO (13) ───────────────────────────────────────
  {
    id: 'v_b1_01', type: 'vocabulary', level: 'B1',
    question: '¿Qué significa "Deadline"?',
    options: ['Inicio', 'Fecha límite', 'Descanso', 'Reunión'],
    correct: 1,
  },
  {
    id: 'v_b1_02', type: 'vocabulary', level: 'B1',
    question: '¿Qué significa "To achieve"?',
    options: ['Fracasar', 'Intentar', 'Lograr', 'Comenzar'],
    correct: 2,
  },
  {
    id: 'v_b1_03', type: 'vocabulary', level: 'B1',
    question: '¿Cómo se dice "investigación" en inglés?',
    options: ['Discovery', 'Research', 'Study', 'Analysis'],
    correct: 1,
  },
  {
    id: 'v_b1_04', type: 'vocabulary', level: 'B1',
    question: '¿Qué significa "Reliable"?',
    options: ['Rápido', 'Confiable', 'Flexible', 'Inteligente'],
    correct: 1,
  },
  {
    id: 'v_b1_05', type: 'vocabulary', level: 'B1',
    question: '¿Qué significa "To complain"?',
    options: ['Completar', 'Cumplir', 'Quejarse', 'Comparecer'],
    correct: 2,
  },
  {
    id: 'v_b1_06', type: 'vocabulary', level: 'B1',
    question: '¿Cómo se dice "medio ambiente" en inglés?',
    options: ['Environment', 'Surroundings', 'Nature', 'Ecosystem'],
    correct: 0,
  },
  {
    id: 'v_b1_07', type: 'vocabulary', level: 'B1',
    question: '¿Qué significa "Salary"?',
    options: ['Ahorro', 'Préstamo', 'Salario', 'Gasto'],
    correct: 2,
  },
  {
    id: 'v_b1_08', type: 'vocabulary', level: 'B1',
    question: '¿Qué significa "Opportunity"?',
    options: ['Obstáculo', 'Decisión', 'Oportunidad', 'Resultado'],
    correct: 2,
  },
  {
    id: 'v_b1_09', type: 'vocabulary', level: 'B1',
    question: '¿Cómo se dice "capacitación" en inglés?',
    options: ['Education', 'Training', 'Learning', 'Course'],
    correct: 1,
  },
  {
    id: 'v_b1_10', type: 'vocabulary', level: 'B1',
    question: '¿Qué significa "To avoid"?',
    options: ['Buscar', 'Evitar', 'Encontrar', 'Aceptar'],
    correct: 1,
  },
  {
    id: 'v_b1_11', type: 'vocabulary', level: 'B1',
    question: '¿Qué significa "Shortage"?',
    options: ['Exceso', 'Escasez', 'Reserva', 'Provisión'],
    correct: 1,
  },
  {
    id: 'v_b1_12', type: 'vocabulary', level: 'B1',
    question: '¿Cómo se dice "ciudadano" en inglés?',
    options: ['Resident', 'Inhabitant', 'Citizen', 'Native'],
    correct: 2,
  },
  {
    id: 'v_b1_13', type: 'vocabulary', level: 'B1',
    question: '¿Qué significa "Approximately"?',
    options: ['Exactamente', 'Aproximadamente', 'Definitivamente', 'Claramente'],
    correct: 1,
  },

  // ── GRAMÁTICA (13) ─────────────────────────────────────────
  {
    id: 'g_b1_01', type: 'grammar', level: 'B1',
    question: 'Completa: "If I ___ more time, I would travel more."',
    options: ['have', 'had', 'will have', 'having'],
    correct: 1,
  },
  {
    id: 'g_b1_02', type: 'grammar', level: 'B1',
    question: 'Completa: "She has been working here ___ five years."',
    options: ['since', 'for', 'ago', 'during'],
    correct: 1,
  },
  {
    id: 'g_b1_03', type: 'grammar', level: 'B1',
    question: 'Completa: "The report ___ by the manager last week."',
    options: ['wrote', 'was written', 'has written', 'writes'],
    correct: 1,
  },
  {
    id: 'g_b1_04', type: 'grammar', level: 'B1',
    question: 'Completa: "I wish I ___ speak Spanish better."',
    options: ['can', 'could', 'will', 'would'],
    correct: 1,
  },
  {
    id: 'g_b1_05', type: 'grammar', level: 'B1',
    question: 'Completa: "By the time she arrived, we ___ dinner."',
    options: ['finish', 'finished', 'had finished', 'have finished'],
    correct: 2,
  },
  {
    id: 'g_b1_06', type: 'grammar', level: 'B1',
    question: 'Completa: "He suggested ___ the meeting earlier."',
    options: ['to reschedule', 'rescheduling', 'reschedule', 'rescheduled'],
    correct: 1,
  },
  {
    id: 'g_b1_07', type: 'grammar', level: 'B1',
    question: 'Completa: "She ___ here for two years when they promoted her."',
    options: ['worked', 'has worked', 'had been working', 'was working'],
    correct: 2,
  },
  {
    id: 'g_b1_08', type: 'grammar', level: 'B1',
    question: 'Completa: "You ___ call before you come — it\'s polite."',
    options: ['must', 'should', 'shall', 'might'],
    correct: 1,
  },
  {
    id: 'g_b1_09', type: 'grammar', level: 'B1',
    question: 'Completa: "The project ___ delayed due to the weather."',
    options: ['got', 'gets', 'getting', 'gotten'],
    correct: 0,
  },
  {
    id: 'g_b1_10', type: 'grammar', level: 'B1',
    question: 'Completa: "She asked me ___ I had seen her keys."',
    options: ['that', 'if', 'what', 'which'],
    correct: 1,
  },
  {
    id: 'g_b1_11', type: 'grammar', level: 'B1',
    question: 'Completa: "Despite ___ hard, he failed the exam."',
    options: ['study', 'studied', 'studying', 'to study'],
    correct: 2,
  },
  {
    id: 'g_b1_12', type: 'grammar', level: 'B1',
    question: 'Completa: "It\'s important that everyone ___ the rules."',
    options: ['follows', 'follow', 'followed', 'following'],
    correct: 1,
  },
  {
    id: 'g_b1_13', type: 'grammar', level: 'B1',
    question: 'Completa: "The results were better than we ___."',
    options: ['expect', 'expecting', 'have expected', 'had expected'],
    correct: 3,
  },

  // ── COMPRENSIÓN (8) ────────────────────────────────────────
  {
    id: 'c_b1_01', type: 'comprehension', level: 'B1',
    context: 'Climate change is one of the biggest challenges of our time. Scientists agree that human activities, especially burning fossil fuels, are the main cause. Governments around the world are working on solutions, but progress is slow.',
    question: '¿Cuál es la causa principal del cambio climático según el texto?',
    options: [
      'Los gobiernos del mundo',
      'Las actividades humanas, especialmente quemar combustibles fósiles',
      'El progreso lento de las soluciones',
      'Los científicos del mundo',
    ],
    correct: 1,
  },
  {
    id: 'c_b1_02', type: 'comprehension', level: 'B1',
    context: 'Remote work has changed how companies operate. Many employees now prefer working from home because it saves commuting time and offers more flexibility. However, some managers worry about productivity and team communication.',
    question: '¿Por qué prefieren trabajar desde casa muchos empleados?',
    options: [
      'Porque los managers lo exigen',
      'Porque es más productivo siempre',
      'Porque ahorra tiempo de transporte y ofrece más flexibilidad',
      'Porque las oficinas están cerradas',
    ],
    correct: 2,
  },
  {
    id: 'c_b1_03', type: 'comprehension', level: 'B1',
    context: 'The new subway line will connect the city center with the airport. Construction started last year and is expected to be completed in 2026. The project will create over two thousand jobs.',
    question: '¿Cuántos empleos creará el proyecto?',
    options: ['Más de 200', 'Más de 1,000', 'Más de 2,000', 'Más de 5,000'],
    correct: 2,
  },
  {
    id: 'c_b1_04', type: 'comprehension', level: 'B1',
    context: 'A healthy diet includes a variety of fruits, vegetables, whole grains, and lean proteins. Experts recommend limiting sugar and processed foods. Regular physical activity is equally important for overall health.',
    question: '¿Qué recomiendan los expertos limitar?',
    options: ['Frutas y verduras', 'Proteínas', 'Azúcar y alimentos procesados', 'Granos integrales'],
    correct: 2,
  },
  {
    id: 'c_b1_05', type: 'comprehension', level: 'B1',
    context: 'Social media platforms have become essential marketing tools for small businesses. They allow companies to reach large audiences at a low cost. However, businesses must post consistently and engage with their followers to be successful.',
    question: '¿Qué deben hacer las empresas para tener éxito en redes sociales?',
    options: [
      'Gastar mucho dinero en publicidad',
      'Publicar constantemente e interactuar con seguidores',
      'Contratar una agencia de marketing',
      'Tener miles de seguidores desde el inicio',
    ],
    correct: 1,
  },
  {
    id: 'c_b1_06', type: 'comprehension', level: 'B1',
    context: 'Libraries are no longer just places to borrow books. Today, many offer digital resources, computer access, language courses, and community events. Their role in society continues to evolve.',
    question: '¿Cómo han cambiado las bibliotecas hoy en día?',
    options: [
      'Han cerrado muchas de ellas',
      'Solo ofrecen libros digitales ahora',
      'Ahora ofrecen muchos más servicios además de libros',
      'Se han convertido en centros comerciales',
    ],
    correct: 2,
  },
  {
    id: 'c_b1_07', type: 'comprehension', level: 'B1',
    context: 'Tourism brings economic benefits to many countries, but it also has negative effects. Popular destinations often suffer from overcrowding, environmental damage, and rising housing costs for local residents.',
    question: '¿Cuál es un efecto negativo del turismo mencionado en el texto?',
    options: [
      'Crea muchos empleos',
      'Aumenta los ingresos del gobierno',
      'Causa daño ambiental y precios de vivienda altos',
      'Mejora la infraestructura local',
    ],
    correct: 2,
  },
  {
    id: 'c_b1_08', type: 'comprehension', level: 'B1',
    context: 'Volunteering abroad can be a valuable experience. It allows people to learn about different cultures, develop new skills, and make a positive impact. However, volunteers should research organizations carefully to ensure their work truly helps local communities.',
    question: '¿Qué deben hacer los voluntarios según el texto?',
    options: [
      'Viajar sin preparación',
      'Investigar bien las organizaciones antes de participar',
      'Solo trabajar con organizaciones grandes',
      'Quedarse en su propio país',
    ],
    correct: 1,
  },

  // ── ESCUCHA (6) ────────────────────────────────────────────
  {
    id: 'l_b1_01', type: 'listening', level: 'B1',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'The deadline for the project has been moved to next Friday',
    options: [
      'The deadline for the project is this Monday',
      'The project was completed last Friday',
      'The deadline for the project has been moved to next Friday',
      'The meeting has been cancelled until further notice',
    ],
    correct: 2,
  },
  {
    id: 'l_b1_02', type: 'listening', level: 'B1',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'If I had more time I would learn to play the piano',
    options: [
      'If I had more money I would buy a piano',
      'If I had more time I would learn to play the guitar',
      'If I had more time I would learn to play the piano',
      'When I have more time I will learn to play the piano',
    ],
    correct: 2,
  },
  {
    id: 'l_b1_03', type: 'listening', level: 'B1',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'She has been living in Canada for three years',
    options: [
      'She has been living in Canada for three years',
      'She lived in Canada three years ago',
      'She has been living in Australia for three years',
      'She will be living in Canada for three more years',
    ],
    correct: 0,
  },
  {
    id: 'l_b1_04', type: 'listening', level: 'B1',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'The report was written by the marketing team last month',
    options: [
      'The report will be written by the marketing team next month',
      'The report was written by the sales team last month',
      'The report was written by the marketing team last month',
      'The report was reviewed by the marketing team last week',
    ],
    correct: 2,
  },
  {
    id: 'l_b1_05', type: 'listening', level: 'B1',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'Despite the rain the event was a great success',
    options: [
      'Because of the rain the event was cancelled',
      'Despite the rain the event was a great success',
      'Although it rained the event had few visitors',
      'Despite the cold the event was a great success',
    ],
    correct: 1,
  },
  {
    id: 'l_b1_06', type: 'listening', level: 'B1',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'I suggest scheduling the meeting for early next week',
    options: [
      'I suggest cancelling the meeting next week',
      'I suggest scheduling the meeting for late next week',
      'She suggested scheduling a call for next week',
      'I suggest scheduling the meeting for early next week',
    ],
    correct: 3,
  },
];
