import type { ExamQuestion } from './examTypes';

export const B2_QUESTIONS: ExamQuestion[] = [
  // ── VOCABULARIO (13) ───────────────────────────────────────
  {
    id: 'v_b2_01', type: 'vocabulary', level: 'B2',
    question: '¿Qué significa "Nevertheless"?',
    options: ['Por lo tanto', 'Sin embargo', 'Además', 'Por ejemplo'],
    correct: 1,
  },
  {
    id: 'v_b2_02', type: 'vocabulary', level: 'B2',
    question: '¿Qué significa "Ambiguous"?',
    options: ['Claro', 'Ambiguo', 'Preciso', 'Detallado'],
    correct: 1,
  },
  {
    id: 'v_b2_03', type: 'vocabulary', level: 'B2',
    question: '¿Cómo se dice "sesgo" en inglés?',
    options: ['Trend', 'Bias', 'Fact', 'Opinion'],
    correct: 1,
  },
  {
    id: 'v_b2_04', type: 'vocabulary', level: 'B2',
    question: '¿Qué significa "Scrutiny"?',
    options: ['Aprobación', 'Escrutinio', 'Propuesta', 'Revisión'],
    correct: 1,
  },
  {
    id: 'v_b2_05', type: 'vocabulary', level: 'B2',
    question: '¿Qué significa "To mitigate"?',
    options: ['Empeorar', 'Eliminar', 'Mitigar', 'Ignorar'],
    correct: 2,
  },
  {
    id: 'v_b2_06', type: 'vocabulary', level: 'B2',
    question: '¿Cómo se dice "brecha" (de desigualdad) en inglés?',
    options: ['Hole', 'Gap', 'Crack', 'Break'],
    correct: 1,
  },
  {
    id: 'v_b2_07', type: 'vocabulary', level: 'B2',
    question: '¿Qué significa "Endeavor"?',
    options: ['Esfuerzo', 'Error', 'Éxito', 'Evidencia'],
    correct: 0,
  },
  {
    id: 'v_b2_08', type: 'vocabulary', level: 'B2',
    question: '¿Qué significa "Deterrent"?',
    options: ['Incentivo', 'Disuasivo', 'Restricción', 'Castigo'],
    correct: 1,
  },
  {
    id: 'v_b2_09', type: 'vocabulary', level: 'B2',
    question: '¿Cómo se dice "perspicaz" en inglés?',
    options: ['Clever', 'Insightful', 'Brilliant', 'Thoughtful'],
    correct: 1,
  },
  {
    id: 'v_b2_10', type: 'vocabulary', level: 'B2',
    question: '¿Qué significa "Accountability"?',
    options: ['Contabilidad', 'Responsabilidad', 'Transparencia', 'Credibilidad'],
    correct: 1,
  },
  {
    id: 'v_b2_11', type: 'vocabulary', level: 'B2',
    question: '¿Qué significa "To undermine"?',
    options: ['Apoyar', 'Fortalecer', 'Socavar', 'Construir'],
    correct: 2,
  },
  {
    id: 'v_b2_12', type: 'vocabulary', level: 'B2',
    question: '¿Cómo se dice "repercusión" en inglés?',
    options: ['Impact', 'Repercussion', 'Consequence', 'Effect'],
    correct: 1,
  },
  {
    id: 'v_b2_13', type: 'vocabulary', level: 'B2',
    question: '¿Qué significa "Preliminary"?',
    options: ['Final', 'Preliminar', 'Temporal', 'Oficial'],
    correct: 1,
  },

  // ── GRAMÁTICA (13) ─────────────────────────────────────────
  {
    id: 'g_b2_01', type: 'grammar', level: 'B2',
    question: 'Completa: "Had she known about the problem, she ___ it sooner."',
    options: ['would fix', 'would have fixed', 'will fix', 'had fixed'],
    correct: 1,
  },
  {
    id: 'g_b2_02', type: 'grammar', level: 'B2',
    question: 'Completa: "Not only ___ late, but he also forgot the documents."',
    options: ['he arrived', 'did he arrive', 'he did arrive', 'arrived he'],
    correct: 1,
  },
  {
    id: 'g_b2_03', type: 'grammar', level: 'B2',
    question: 'Completa: "The new policy ___ to all employees regardless of their position."',
    options: ['applying', 'applied', 'applies', 'apply'],
    correct: 2,
  },
  {
    id: 'g_b2_04', type: 'grammar', level: 'B2',
    question: 'Completa: "It is high time the government ___ action on housing."',
    options: ['takes', 'took', 'has taken', 'take'],
    correct: 1,
  },
  {
    id: 'g_b2_05', type: 'grammar', level: 'B2',
    question: 'Completa: "Rarely ___ such a compelling argument in a debate."',
    options: ['I have heard', 'have I heard', 'I heard', 'did I heard'],
    correct: 1,
  },
  {
    id: 'g_b2_06', type: 'grammar', level: 'B2',
    question: 'Completa: "She is said ___ the most influential scientist of her generation."',
    options: ['to be', 'being', 'that she is', 'to have been'],
    correct: 0,
  },
  {
    id: 'g_b2_07', type: 'grammar', level: 'B2',
    question: 'Completa: "The data ___ to support the original hypothesis."',
    options: ['appear', 'appears', 'appearing', 'are appearing'],
    correct: 1,
  },
  {
    id: 'g_b2_08', type: 'grammar', level: 'B2',
    question: 'Completa: "I would rather you ___ about this to anyone."',
    options: ['not talk', 'not talked', 'did not talk', 'not to talk'],
    correct: 0,
  },
  {
    id: 'g_b2_09', type: 'grammar', level: 'B2',
    question: 'Completa: "The manuscript ___ to date back to the twelfth century."',
    options: ['is believed', 'believes', 'has believed', 'was believing'],
    correct: 0,
  },
  {
    id: 'g_b2_10', type: 'grammar', level: 'B2',
    question: 'Completa: "No sooner ___ the speech than the audience applauded."',
    options: ['he finished', 'had he finished', 'he had finished', 'did he finish'],
    correct: 1,
  },
  {
    id: 'g_b2_11', type: 'grammar', level: 'B2',
    question: 'Completa: "Were she to apply for the position, she ___ it."',
    options: ['would get', 'will get', 'gets', 'would have gotten'],
    correct: 0,
  },
  {
    id: 'g_b2_12', type: 'grammar', level: 'B2',
    question: 'Completa: "The longer you wait, ___ it will be to resolve."',
    options: ['harder', 'more hard', 'the harder', 'most hard'],
    correct: 2,
  },
  {
    id: 'g_b2_13', type: 'grammar', level: 'B2',
    question: 'Completa: "The CEO, along with the board members, ___ to resign."',
    options: ['were asked', 'was asked', 'are asked', 'have been asked'],
    correct: 1,
  },

  // ── COMPRENSIÓN (8) ────────────────────────────────────────
  {
    id: 'c_b2_01', type: 'comprehension', level: 'B2',
    context: 'The concept of emotional intelligence, popularized by psychologist Daniel Goleman, refers to the ability to recognize, understand, and manage our own emotions while also being aware of and influencing the emotions of others. Research suggests that emotional intelligence may be a better predictor of professional success than traditional IQ.',
    question: 'Según el texto, ¿qué podría predecir mejor el éxito profesional?',
    options: ['El IQ tradicional', 'La inteligencia emocional', 'Las habilidades técnicas', 'La experiencia laboral'],
    correct: 1,
  },
  {
    id: 'c_b2_02', type: 'comprehension', level: 'B2',
    context: 'Artificial intelligence is transforming industries at an unprecedented pace. While it promises increased efficiency and innovation, critics argue that without proper regulation, AI could exacerbate inequality and threaten privacy. The challenge lies in harnessing its potential while mitigating its risks.',
    question: '¿Cuál es el desafío principal mencionado respecto a la IA?',
    options: [
      'Hacer la IA más rápida',
      'Reemplazar todos los trabajos humanos',
      'Aprovechar su potencial mientras se mitigan sus riesgos',
      'Eliminar la desigualdad mediante la IA',
    ],
    correct: 2,
  },
  {
    id: 'c_b2_03', type: 'comprehension', level: 'B2',
    context: 'Urban farming is gaining popularity as cities grapple with food security and sustainability. Rooftop gardens, vertical farms, and community plots are transforming unused spaces into productive land. Proponents argue these initiatives reduce carbon footprints and strengthen local food systems.',
    question: '¿Qué argumentan los defensores de la agricultura urbana?',
    options: [
      'Que es más rentable que la agricultura tradicional',
      'Que reduce la huella de carbono y fortalece sistemas alimentarios locales',
      'Que puede reemplazar completamente la agricultura rural',
      'Que solo funciona en ciudades grandes',
    ],
    correct: 1,
  },
  {
    id: 'c_b2_04', type: 'comprehension', level: 'B2',
    context: 'The gig economy has fundamentally altered labor markets. While it offers workers unprecedented flexibility, it has also eroded traditional job security and benefits. Policymakers face the complex task of regulating this sector without stifling its innovation.',
    question: '¿Cuál es el dilema que enfrentan los legisladores según el texto?',
    options: [
      'Cómo eliminar la economía gig',
      'Cómo regular el sector sin frenar su innovación',
      'Cómo ofrecer más flexibilidad a los trabajadores',
      'Cómo aumentar los beneficios de todos los trabajadores',
    ],
    correct: 1,
  },
  {
    id: 'c_b2_05', type: 'comprehension', level: 'B2',
    context: 'Cognitive biases are systematic errors in thinking that affect the judgments and decisions people make. Confirmation bias — the tendency to favor information that confirms existing beliefs — is particularly prevalent. Awareness of these biases is the first step toward more rational decision-making.',
    question: '¿Qué es el sesgo de confirmación según el texto?',
    options: [
      'La tendencia a tomar decisiones rápidas',
      'La capacidad de confirmar hechos',
      'La tendencia a favorecer información que confirma creencias existentes',
      'El proceso de razonamiento lógico',
    ],
    correct: 2,
  },
  {
    id: 'c_b2_06', type: 'comprehension', level: 'B2',
    context: 'Microplastics have been detected in virtually every ecosystem on Earth, from the deepest ocean trenches to Arctic ice. Scientists are increasingly concerned about their impact on human health, as these particles have been found in human blood and lung tissue. The primary sources are synthetic textiles, tire dust, and plastic packaging.',
    question: '¿Cuáles son las fuentes principales de microplásticos según el texto?',
    options: [
      'Los océanos y glaciares',
      'Textiles sintéticos, polvo de llantas y empaques plásticos',
      'Las industrias químicas y farmacéuticas',
      'Los vehículos eléctricos y paneles solares',
    ],
    correct: 1,
  },
  {
    id: 'c_b2_07', type: 'comprehension', level: 'B2',
    context: 'The paradox of choice suggests that having too many options can lead to decision paralysis and decreased satisfaction. Psychologist Barry Schwartz argues that while some choice is better than none, an excess of options places undue burden on individuals and can result in regret even after making a decision.',
    question: '¿Qué plantea la paradoja de la elección?',
    options: [
      'Que más opciones siempre llevan a mejores decisiones',
      'Que tener demasiadas opciones puede generar parálisis e insatisfacción',
      'Que las personas prefieren no tener opciones',
      'Que el arrepentimiento surge solo por malas decisiones',
    ],
    correct: 1,
  },
  {
    id: 'c_b2_08', type: 'comprehension', level: 'B2',
    context: 'Whistleblowing — the act of exposing wrongdoing within an organization — is both morally complex and legally precarious. While whistleblowers often serve the public interest by revealing corruption or safety violations, they frequently face retaliation. Many countries have enacted legislation to protect them, though enforcement remains inconsistent.',
    question: '¿Qué problema enfrentan frecuentemente los denunciantes (whistleblowers)?',
    options: [
      'Reciben premios por su valentía',
      'Enfrentan represalias',
      'No son tomados en serio por las autoridades',
      'Deben pagar multas legales',
    ],
    correct: 1,
  },

  // ── ESCUCHA (6) ────────────────────────────────────────────
  {
    id: 'l_b2_01', type: 'listening', level: 'B2',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'Despite the economic uncertainty the company managed to increase its revenue by fifteen percent',
    options: [
      'The company failed to meet its revenue targets this quarter',
      'Due to economic growth profits rose by fifty percent',
      'Despite the economic uncertainty the company managed to increase its revenue by fifteen percent',
      'The economic situation forced the company to reduce its workforce significantly',
    ],
    correct: 2,
  },
  {
    id: 'l_b2_02', type: 'listening', level: 'B2',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'Not only did she exceed expectations but she also mentored junior colleagues',
    options: [
      'She exceeded expectations and received a promotion',
      'Not only did she exceed expectations but she also mentored junior colleagues',
      'Not only did she meet expectations but she also trained new staff',
      'She barely met expectations despite mentoring junior colleagues',
    ],
    correct: 1,
  },
  {
    id: 'l_b2_03', type: 'listening', level: 'B2',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'Had the team been better prepared the outcome would have been different',
    options: [
      'If the team prepares better the outcome will be different',
      'The team was well prepared but the outcome was still poor',
      'Had the team been better prepared the outcome would have been different',
      'Because the team prepared well the outcome was positive',
    ],
    correct: 2,
  },
  {
    id: 'l_b2_04', type: 'listening', level: 'B2',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'The legislation is unlikely to pass without significant amendments',
    options: [
      'The legislation passed without any amendments last month',
      'The legislation is unlikely to pass without significant amendments',
      'The legislation will likely pass with minor amendments',
      'The legislation was rejected due to significant opposition',
    ],
    correct: 1,
  },
  {
    id: 'l_b2_05', type: 'listening', level: 'B2',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'Rarely have we witnessed such a profound shift in consumer behavior',
    options: [
      'We have never seen such changes in consumer behavior before',
      'Rarely have we witnessed such a profound shift in consumer behavior',
      'We have rarely seen such minor changes in market trends',
      'Such changes in consumer behavior are quite common nowadays',
    ],
    correct: 1,
  },
  {
    id: 'l_b2_06', type: 'listening', level: 'B2',
    question: 'Escucha y selecciona lo que escuchaste:',
    audio: 'The research findings challenge long held assumptions about early childhood development',
    options: [
      'The research findings support long held assumptions about early childhood development',
      'The research findings challenge recent theories about teenage development',
      'The research findings challenge long held assumptions about early childhood development',
      'New research findings confirm assumptions about childhood learning',
    ],
    correct: 2,
  },
];
